### ISSUE TITLE
Crash on PocketMine-MP Version 4.3.2

### ISSUE THREAD

**Issue by Tuvqlu** [thebigcrafter/KygekTagsShop#14]
![C3961F4F-D3C8-42C6-9577-405220DACD5C](https://user-images.githubusercontent.com/98550458/168442550-28894927-905f-455a-a0df-47349a2c4495.jpeg)

**Comment by KygekDev** [comment]
@Tuvqlu What is the PM version you were using when loading the plugin?

**Comment by Tuvqlu** [comment]
4.3.2

**Comment by MintoD** [comment]
Thank you for reporting. I fixed it. You can use version 1.0.0-RC or later to avoid this issue.

**Comment by Tuvqlu** [comment]
Thankyou for fixing :)

**Comment by Tuvqlu** [comment]
It still crashes for me by the way

**Comment by MintoD** [comment]
> What is RC, lol

A release candidate (RC) is a beta version with potential to be a stable product, which is ready to release unless significant bugs emerge.
You can read more [here.](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate)

**Comment by MintoD** [comment]
> It still crashes for me by the way

Can you give me a crash log?

**Comment by Tuvqlu** [comment]
![C3B7DFC9-4C13-4B2F-8F22-52D1EE635303](https://user-images.githubusercontent.com/98550458/170252891-5c4670d6-1764-44b3-87cd-8be31b51ab64.jpeg)

**Comment by MintoD** [comment]
Fixed it! Thanks for reporting.
