### ISSUE TITLE
Suggestion: Tags inventory

### ISSUE THREAD

**Issue by FoodyYoutoob** [thebigcrafter/KygekTagsShop#8]
Can you make a tags saving feature so tags can save to something after buying them. You can view them when clicking a button in the form saying inventory.

**Comment by KygekDev** [comment]
You can do that by making or modifying a plugin which uses the KygekTagsShop API.

**Comment by FoodyYoutoob** [comment]
What plugin?

**Comment by dugo3number2** [comment]
> What plugin?

As of now, none. As soon as I have a way to test Bedrock plugins again I'd be glad to help make one for you.

**Comment by KygekDev** [comment]
> As of now, none.

No, he should make a plugin. We already provided APIs to use.

**Comment by Tuvqlu** [comment]
I agree :d #15

**Comment by NhanAZ** [comment]
> You can do that by making or modifying a plugin which uses the KygekTagsShop API.

I agree, it's time to close this old issue.
